### PR TITLE
some style flattening

### PR DESCRIPTION
**Pull request by r3trosteve**
flattened some styles and replaced some assets

### CODE REVIEW

**Comment by mattmischuk** [comment]
Ouch this was a mistake

**Comment by r3trosteve** [comment]
@mattmischuk a bit harsh... :) maybe some more constructive feedback?

FYI the updates were basically just a test of how the whole thing works end to end. You can expect to see further updates soon.

**Comment by mattmischuk** [comment]
I guess so, but it breaks my heart to see the beautiful design of RiotHQ products degrade. It's just the details weren't executed correctly. The header has lost visual hierarchy and the toggle doesn't fit the header and doesn't fit Apples HUI guidelines. Also the icons are too large and heavy weighted. Also not rounded to the nearest pixel. I'll submit a PR.

**Comment by r3trosteve** [comment]
That's more like it. I'll be opening up the roadmap for anvil which includes the UI direction which has also been worked on in parallel as part of thinking about the whole suite of products and the unifying of design. Whilst I'm not and out and out UI expert, right now my priority is getting these things moving again and we'll work on the details. The more support I can get on that from people like yourself, the better we'll be for it. Please PR away...

**Comment by r3trosteve** [comment]
screen shot 2015-09-14 at 23 04 22

This is more like what's coming...

**Comment by mattmischuk** [comment]
Much better :)



Matt Mischuk

**Pull request merged**
